services:
  db:
    container_name: weather_db
    image: postgres:14.17
    environment:
      POSTGRES_USER: weather_user
      POSTGRES_PASSWORD: weather_pass
      POSTGRES_DB: weather_data
    ports:
      - "5000:5432"
    volumes:
      - ./postgres/data:/var/lib/postgresql/data
      - ./postgres/airflow_init.sql:/docker-entrypoint-initdb.d/airflow_init.sql
    networks:
      - my-network
  af:
    container_name: weather_af
    image: apache/airflow:3.0.0 
    ports:
      - "8000:8080"
    environment:
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
      AIRFLOW__CORE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow_user:airflow_pass@db:5432/airflow_db
    volumes:
      - ./airflow/dags:/opt/airflow/dags
      - ./api-request:/opt/airflow/api_request
      - ./var/run/docker.sock:/var/run/docker.sock
    depends_on:
      - db
    networks:
      - my-network
    command: >
      bash -c "airflow db migrate &&
               airflow standalone"
  dbt:
    container_name: weather_dbt
    image: ghcr.io/dbt-labs/dbt-postgres:1.9.latest
    volumes:
      - ./dbt/my_project/my_project:/usr/app
      - ./dbt:/root/.dbt
    working_dir: /usr/app
    environment:
      DBT_PROFILES_DIR: "/root/.dbt"
    depends_on:
      - db
    networks:
      - my-network
    command: debug
networks:
      my-network:
        driver: bridge